# This file needs to have chmod 400 permissions

# oauth client id and secret required for the application.
client_id: '<ID>'
client_secret: '<SECRET>'

# url of your deployed app
# for local testing, you could your localhost with a TCP port app will listen on: e.g. http://127.0.0.1:8100/
# ensure the url specified (as well as localhost) here has been verified in your client
app_url: 'http://127.0.0.1:3978'
