name: Run Tests
on: [push]
jobs:
  run-tests:
    runs-on: ubuntu-latest
    steps:
      - name: Run tests
        shell: Rscript {0}
        run: |
          install.packages("devtools")
          devtools::test()
